-- Table structure for table `wishlist`
CREATE TABLE IF NOT EXISTS public.wishlist
(
    wishlist_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    inv_id integer NOT NULL,
    CONSTRAINT wishlist_pkey PRIMARY KEY (wishlist_id),
    CONSTRAINT fk_account FOREIGN KEY (account_id)
        REFERENCES public.account (account_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
        REFERENCES public.inventory (inv_id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
